### ISSUE TITLE
Help on how to use it!

### ISSUE THREAD

**Issue by SidraFirdous** [ehermes/micki#1]
Thank you for writing this code and sharing it on Github. 

Could you please provide a more elaborate README on how to exactly use this program. That will be very helpful.

**Comment by YaseminBasdogan** [comment]
Yes, I would also love to use your code so instructions would be appreciated!

**Comment by ehermes** [comment]
This was my Ph.D. project, and I have since graduated and am now working on something (almost) completely unrelated.

That said, this project isn't abandoned! Please take a look at [jrschmidt2/micki](https://github.com/jrschmidt2/micki) for an actively-maintained fork of this project.

You can also learn more about how Micki works and how to use it from [our recent publication](https://aip.scitation.org/doi/full/10.1063/1.5109116).
